export {DeletedTeachers} from "./ui/deletedTeachers/deletedTeachers"
export {Teachers} from "./ui/teachers/teachers"
export {fetchTeachersData} from "./model/teacherThunk"
export {getTeachers} from "./model/selector/teacherSelector"
export {default as teachers} from "./model/teacherSlice"